services:
  bolt-ai:
    image: bolt-ai:production
    build:
      context: .
      dockerfile: Dockerfile
      target: bolt-ai-production
    ports:
      - "5173:5173"
    env_file: ".env.local"
    environment:
      - NODE_ENV=production
      - COMPOSE_PROFILES=production
      # No strictly neded but serving as hints for Coolify
      - PORT=5173
      - GROQ_API_KEY=${GROQ_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPEN_ROUTER_API_KEY=${OPEN_ROUTER_API_KEY}
      - GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY}
      - OLLAMA_API_BASE_URL=${OLLAMA_API_BASE_URL}
      - VITE_LOG_LEVEL=${VITE_LOG_LEVEL:-debug}
      - RUNNING_IN_DOCKER=true
    extra_hosts:
      - "host.docker.internal:host-gateway"      
    command: pnpm run dockerstart
    profiles:
      - production  # This service only runs in the production profile

  bolt-ai-dev:
    image: bolt-ai:development
    build:
      target: bolt-ai-development
    environment:
      - NODE_ENV=development  # Set the environment to development
      - VITE_HMR_PROTOCOL=ws  # WebSocket protocol for HMR
      - VITE_HMR_HOST=0.0.0.0  # Host for HMR to allow external access
      - VITE_HMR_PORT=5173  # Port for HMR
      - CHOKIDAR_USEPOLLING=true  # Enable polling for file changes
      - WATCHPACK_POLLING=true  # Enable polling for webpack
      - PORT=5173  # Application port
      - GROQ_API_KEY=${GROQ_API_KEY}  # GROQ API Key
      - OPENAI_API_KEY=${OPENAI_API_KEY}  # OpenAI API Key
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}  # Anthropic API Key
      - OPEN_ROUTER_API_KEY=${OPEN_ROUTER_API_KEY}  # Open Router API Key
      - GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY}  # Google Generative AI API Key
      - OLLAMA_API_BASE_URL=${OLLAMA_API_BASE_URL}  # Ollama API Base URL
      - VITE_LOG_LEVEL=${VITE_LOG_LEVEL:-debug}  # Log level for Vite
      - RUNNING_IN_DOCKER=true  # Flag to indicate running in Docker
    extra_hosts:
      - "host.docker.internal:host-gateway"      
    volumes:
      - type: bind
        source: .
        target: /app
        consistency: cached
      - /app/node_modules
    ports:
      - "5173:5173"  # Same port, no conflict as only one runs at a time
    command: pnpm run dev --host 0.0.0.0
    profiles: ["development"]  # Set development as the default profile
